{
    'name': 'NC Management',
    'summary': 'NC Management module',
    'version': '11.0.1.0',
    'category': 'Tools',
    'author': 'Your Name',

    'depends': ['base', 'hr', 'mail', 'web'],
    'data': [
        'security/quality_groups.xml',
        'security/ir.model.access.csv',
        'security/quality_rules.xml',
        'security/nc_rules.xml',
        'data/sequences.xml',
        'data/nc_types.xml',
        'data/revisions.xml',
        'data/mail_template.xml',
        'data/ir_cron.xml',
        'wizard/send_fnc_wizard.xml',
        'wizard/send_fac_wizard.xml',
        'wizard/send_plan_wizard.xml',
        'wizard/reply_wizard.xml',
        'wizard/number_generator_wizard.xml',
        'wizard/export_plan_wizard.xml',
        'wizard/export_smi_analysis_wizard.xml',
        'wizard/consolidate_wizard.xml',
        'wizard/consolidate_improvement_wizard.xml',
        'wizard/plan_efficacite_wizard.xml',
        'wizard/plan_number_wizard.xml',
        'wizard/consulter_version_wizard.xml',
        'wizard/consulter_version_improvement_wizard.xml',
        'reports/report_fnc.xml',
        'reports/report_fac.xml',
        'reports/report_revision.xml',
        'reports/report_plan_global.xml',
        'reports/report_plan_action_smi_pdf.xml',
        'views/assets.xml',
        'views/views.xml',
        'views/plan_action_smi.xml',
        'views/smi_improvement_plan_views.xml',
        'views/smi_global_plan_views.xml',
        'views/dashboard.xml',
        'views/form_template_views.xml',
        'data/default_fnc_template.xml',
        'data/default_fac_template.xml',
        'data/default_plan_smi_template.xml',
    ],
    'qweb': [
        'static/src/xml/dashboard.xml',
    ],

    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
