from . import send_fnc_wizard
from . import send_fac_wizard
from . import send_plan_wizard
from . import new_revision_wizard
from . import number_generator_wizard
from . import export_plan_wizard
from . import export_smi_analysis_wizard
from . import reply_wizard
from . import consolidate_wizard
from . import consolidate_improvement_wizard
from . import plan_efficacite_wizard
from . import plan_number_wizard
